spring.application.name=ridhitek-image-plugin
server.port=8082

# Database Configuration (Verification Plugin)
spring.datasource.url=jdbc:postgresql://localhost:5432/ridhitek_image_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Image Storage Configuration (Default to local)
app.image.storage.path=D:/RIVO_10-02/Images
app.image.base.url=http://localhost:8181
# GCP Settings (prod profile)
gcp.storage.bucket-name=ridhitek-uat-images-2025
Map.entry: SCOPE_admin, SCOPE_admin:read
